services:
  php:
    build:
      context: docker/php
    container_name: ${PROJECT_NAME}_php
    working_dir: /var/www/${PROJECT_NAME}
    volumes:
      - .:/var/www/${PROJECT_NAME}
    depends_on:
      - database

  nginx:
    image: nginx:latest
    container_name: ${PROJECT_NAME}_nginx
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/${PROJECT_NAME}
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - PROJECT_NAME=${PROJECT_NAME}
    depends_on:
      - php

  database:
    image: mysql:8.0
    container_name: ${PROJECT_NAME}_db
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: