services:
  php:
    build:
      context: docker/php
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - PROJECT_NAME=${PROJECT_NAME}
    environment:
      - USER_ID=${USER_ID}
      - GROUP_ID=${GROUP_ID}
      - PROJECT_NAME=${PROJECT_NAME}